### ISSUE TITLE
Issues with two colabs

### ISSUE THREAD

**Issue by ahmadgjh** [google/dopamine#100]
I'm trying to run:

https://colab.research.google.com/github/google/dopamine/blob/master/dopamine/colab/load_statistics.ipynb

and

https://colab.research.google.com/github/google/dopamine/blob/master/dopamine/colab/agents.ipynb

connected to hosted runtime.

I got two issues:

For this colab:
https://colab.research.google.com/github/google/dopamine/blob/master/dopamine/colab/load_statistics.ipynb

I got this error when loading the summarized sample data and add it to the global data frame:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-86f0cf28cd53> in <module>()
     17 for game in GAMES:
     18   experimental_data[game] = experimental_data[game].merge(
---> 19       sample_data[sample_data.game == game], how='outer')

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py in merge(self, right, how, on, left_on, right_on, left_index, right_index, sort, suffixes, copy, indicator, validate)
   6387                      right_on=right_on, left_index=left_index,
   6388                      right_index=right_index, sort=sort, suffixes=suffixes,
-> 6389                      copy=copy, indicator=indicator, validate=validate)
   6390 
   6391     def round(self, decimals=0, *args, **kwargs):

/usr/local/lib/python3.6/dist-packages/pandas/core/reshape/merge.py in merge(left, right, how, on, left_on, right_on, left_index, right_index, sort, suffixes, copy, indicator, validate)
     59                          right_index=right_index, sort=sort, suffixes=suffixes,
     60                          copy=copy, indicator=indicator,
---> 61                          validate=validate)
     62     return op.get_result()
     63 

/usr/local/lib/python3.6/dist-packages/pandas/core/reshape/merge.py in __init__(self, left, right, how, on, left_on, right_on, axis, left_index, right_index, sort, suffixes, copy, indicator, validate)
    553         # validate the merge keys dtypes. We may need to coerce
    554         # to avoid incompat dtypes
--> 555         self._maybe_coerce_merge_keys()
    556 
    557         # If argument passed to validate,

/usr/local/lib/python3.6/dist-packages/pandas/core/reshape/merge.py in _maybe_coerce_merge_keys(self)
    981             elif ((is_numeric_dtype(lk) and not is_bool_dtype(lk))
    982                     and not is_numeric_dtype(rk)):
--> 983                 raise ValueError(msg)
    984             elif (not is_numeric_dtype(lk)
    985                     and (is_numeric_dtype(rk) and not is_bool_dtype(rk))):

ValueError: You are trying to merge on float64 and object columns. If you wish to proceed you should use pd.concat

and for this colab:
https://colab.research.google.com/github/google/dopamine/blob/master/dopamine/colab/agents.ipynb

I got this error when loading the training logs:

Reading statistics from: /tmp/colab_dope_run/random_dqn/Asterix//logs/log_199
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-12-2d49060d07eb> in <module>()
----> 1 random_dqn_data = colab_utils.read_experiment(LOG_PATH, verbose=True)
      2 random_dqn_data['agent'] = 'MyRandomDQN'
      3 random_dqn_data['run_number'] = 1
      4 experimental_data[GAME] = experimental_data[GAME].merge(random_dqn_data,
      5                                                         how='outer')

/usr/local/lib/python3.6/dist-packages/dopamine/colab/utils.py in read_experiment(log_path, parameter_set, job_descriptor, iteration_number, summary_keys, verbose)
    276         experiment_path, iteration_number=iteration_number, verbose=verbose)
    277 
--> 278     summary = summarize_data(raw_data, summary_keys)
    279     for iteration in range(last_iteration):
    280       # The row contains all the parameters, the iteration, and finally the

/usr/local/lib/python3.6/dist-packages/dopamine/colab/utils.py in summarize_data(data, summary_keys)
    195       # If there is no data for this iteration, use the previous'.
    196       if iter_key in data:
--> 197         current_value = np.mean(data[iter_key][key])
    198       summary[key].append(current_value)
    199 

KeyError: 'eval_episode_returns'

How to fix it?

Thank you.

**Comment by psc-g** [comment]
hi, i pushed two changes recently that fixes at least one of your errors. could you try again?
if it doesn't work, could you let me know what version of dopamine is being installed? it will be printed out when you run the first cell in the colab.

also, the links your posted don't appear to work. if you're still having issues could you let me know what cells are causing the errors?

**Comment by ahmadgjh** [comment]
For the load_statistics colab (https://colab.research.google.com/github/google/dopamine/blob/master/dopamine/colab/load_statistics.ipynb) I tried again with the latest version of dopamine 2.0.3 and it worked no issues, 

 
For the agents colab (https://colab.research.google.com/github/google/dopamine/blob/master/dopamine/colab/agents.ipynb) I still get an error in example 1 when loading the training logs:

Cell:
# @title Load the training logs.
random_dqn_data = colab_utils.read_experiment(LOG_PATH, verbose=True)
random_dqn_data['agent'] = 'MyRandomDQN'
random_dqn_data['run_number'] = 1
experimental_data[GAME] = experimental_data[GAME].merge(random_dqn_data,
                                                        how='outer')

Output:
Reading statistics from: /tmp/colab_dope_run/random_dqn/Asterix//logs/log_199
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-9-2d49060d07eb> in <module>()
----> 1 random_dqn_data = colab_utils.read_experiment(LOG_PATH, verbose=True)
      2 random_dqn_data['agent'] = 'MyRandomDQN'
      3 random_dqn_data['run_number'] = 1
      4 experimental_data[GAME] = experimental_data[GAME].merge(random_dqn_data,
      5                                                         how='outer')

/usr/local/lib/python3.6/dist-packages/dopamine/colab/utils.py in read_experiment(log_path, parameter_set, job_descriptor, iteration_number, summary_keys, verbose)
    277         experiment_path, iteration_number=iteration_number, verbose=verbose)
    278 
--> 279     summary = summarize_data(raw_data, summary_keys)
    280     for iteration in range(last_iteration):
    281       # The row contains all the parameters, the iteration, and finally the

/usr/local/lib/python3.6/dist-packages/dopamine/colab/utils.py in summarize_data(data, summary_keys)
    196       # If there is no data for this iteration, use the previous'.
    197       if iter_key in data:
--> 198         current_value = np.mean(data[iter_key][key])
    199       summary[key].append(current_value)
    200 

KeyError: 'eval_episode_returns'

**Comment by psc-g** [comment]
thanks for raising this.
the problem was caused because at one point i switched to TrainRunner, which doesn't generate eval curves. i'll have a fix out soon, but until then you can fix it by using these lines in the cells to load the training logs, instead of what's currently in there:
```
random_dqn_data = colab_utils.read_experiment(
    LOG_PATH, verbose=True, summary_keys=['train_episode_returns'])
```
and
```
sticky_data = colab_utils.read_experiment(
    LOG_PATH, verbose=True, summary_keys=['train_episode_returns'])
```

**Comment by psc-g** [comment]
this was fixed here: https://github.com/google/dopamine/commit/826f172ff24df00ab2f8cf4f6f0d352df17acdfe
